tcpdump: updated to 4.99.3

diff --git a/trunk/user/tcpdump/tcpdump-4.99.3/Makefile.in b/trunk/user/tcpdump/tcpdump-4.99.3/Makefile.in
--- a/trunk/user/tcpdump/tcpdump-4.99.3/Makefile.in
+++ b/trunk/user/tcpdump/tcpdump-4.99.3/Makefile.in
@@ -416,9 +416,9 @@ CLEANFILES = $(PROG) $(OBJ) $(LIBNETDISSECT_OBJ)
 EXTRA_DIST = \
 	CHANGES \
 	CMakeLists.txt \
-	CONTRIBUTING \
+	CONTRIBUTING.md \
 	CREDITS \
-	INSTALL.txt \
+	INSTALL.md \
 	LICENSE \
 	Makefile-devel-adds \
 	Makefile.in \
@@ -438,6 +438,7 @@ EXTRA_DIST = \
 	configure \
 	configure.ac \
 	doc/README.aix.md \
+	doc/README.NetBSD.md \
 	doc/README.solaris.md \
 	doc/README.Win32.md \
 	install-sh \
@@ -526,7 +527,7 @@ clean:
 
 distclean:
 	rm -f $(CLEANFILES) Makefile config.cache config.log config.status \
-	    config.h gnuc.h os-proto.h stamp-h stamp-h.in $(PROG).1 \
+	    config.h os-proto.h stamp-h stamp-h.in $(PROG).1 \
 	    libnetdissect.a tests/.failed tests/.passed \
 	    tests/failure-outputs.txt
 	rm -rf autom4te.cache tests/DIFF tests/NEW
@@ -553,6 +554,57 @@ releasetar:
 	    git archive --prefix="$$TAG"/ -o "$$TAG".tar.gz HEAD \
 	    $(RELEASE_FILES) && \
 	    echo "No $$TAG tag. Archive build from HEAD."; \
+	fi
+
+releasecheck: releasetar
+	@TAG=$(PROG)-`cat VERSION` && \
+	INSTALL_DIR=/tmp/install_"$$TAG"_$$$$ && \
+	DIR=`pwd` && \
+	cd /tmp && \
+	rm -rf "$$TAG" && \
+	rm -rf "$$INSTALL_DIR" && \
+	tar xf "$$DIR"/"$$TAG".tar.gz && \
+	cd "$$TAG" && \
+	echo "[$@] $$ ./configure --enable-smb --quiet --prefix=$$INSTALL_DIR" && \
+	./configure --enable-smb --quiet --prefix="$$INSTALL_DIR" && \
+	echo '[$@] $$ make -s all check' && \
+	make -s all check >/dev/null && \
+	echo '[$@] $$ make -s install' && \
+	make -s install && \
+	cd .. && \
+	rm -rf "$$TAG" && \
+	rm -rf "$$INSTALL_DIR" && \
+	tar xf "$$DIR"/"$$TAG".tar.gz && \
+	cd "$$TAG" && \
+	mkdir build && \
+	cd build && \
+	echo '[$@] $$ cmake -DENABLE_SMB=yes [...] ..' && \
+	cmake -DENABLE_SMB=yes \
+	    -DCMAKE_INSTALL_PREFIX="$$INSTALL_DIR" \
+	    -DCMAKE_MESSAGE_LOG_LEVEL=NOTICE \
+	    -DCMAKE_RULE_MESSAGES=OFF \
+	    -DCMAKE_INSTALL_MESSAGE=NEVER \
+	    .. && \
+	echo '[$@] $$ make -s all check' && \
+	make -s all check >/dev/null && \
+	echo '[$@] $$ make -s install' && \
+	make -s install && \
+	cd ../.. && \
+	rm -rf "$$TAG" && \
+	rm -rf "$$INSTALL_DIR" && \
+	echo '[$@] Done.'
+
+whitespacecheck:
+	@# trailing space(s)?
+	@if git grep -I -n ' $$' $$(git ls-files|grep -v '^tests/'); then \
+	    echo 'Error: Trailing space(s).'; \
+	    exit 1; \
+	fi
+	@# trailing tab(s)?
+	@# install-sh has a tab at the end of one line
+	@if git grep -I -n '	$$' $$(git ls-files|grep -vE '^(tests/|install-sh$$)'); then \
+	    echo 'Error: Trailing tabs(s).'; \
+	    exit 1; \
 	fi
 
 testlist:
